apiVersion: v1
kind: Service
metadata:
  name: regattameldung
spec:
  selector:
    app: rmweb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sksvsqlserver
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rm-deployment
spec:
  selector:
    matchLabels:
      app: rmweb
  replicas: 2
  template:
    metadata:
      labels:
        app: rmweb
    spec:
      containers:
      - name: rmweb
        image: tuxone/regattameldung:1.0
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
spec:
  selector:
    matchLabels:
      app: sqlserver
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
        - name: SA_PASSWORD
          value: 'Geheim@123'
        - name: ACCEPT_EULA
          value: 'Y'
        ports:
        - containerPort: 1433